name: Update Fire Data

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths: [ '.github/workflows/update-fire-data.yml' ]

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the action to write to the repository
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas python-dateutil
    
    - name: Fetch fire data
      env:
        NASA_FIRMS_MAP_KEY: ${{ secrets.NASA_FIRMS_MAP_KEY }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        echo "🚀 Starting fire data fetch at $(date)"
        timeout 10m python scripts/fetch_fire_data.py
        echo "✅ Fire data fetch completed at $(date)"
      timeout-minutes: 12
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push data
      run: |
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🔥 Update fire data - $(date -u +"%Y-%m-%d %H:%M UTC")"
          git push
        fi
